### ISSUE TITLE
Staticman error

### ISSUE THREAD

**Issue by VincentTam** [ngehlert/developapa#14]
I couldn't send comment from https://developapa.com/static-site-generators/.

![Screenshot from 2019-08-28 22-51-45](https://user-images.githubusercontent.com/5748535/63891868-79860c80-c9e6-11e9-84ea-3f531b36f585.png)

Request JSON:

```json
{
  "fields": {
    "message": "Does your *comment* system support Markdown?\n\n> Test block quote.",
    "name": "Vin100 Tam",
    "page": "static-site-generators"
  }
}
```

Response JSON:

```json
{
  "success":false,
  "errorCode":"MISSING_PARAMS"
}
```

**Comment by ngehlert** [comment]
thanks for the feedback, really appreciate it. will look into it

**Comment by ngehlert** [comment]
hm thats weird, so when I try to send the same comment with your params it seem to work...

check this PR: https://github.com/ngehlert/developapa/pull/16

will dig deeper into this. maybe it was some hickup of the backend provider that creates the PRs.

And to your questions, no actually don't know if Markdown is supported, never tested it :) but I assume it should work

**Comment by VincentTam** [comment]
@ngehlert Thx for comments.  I'm closing this since I'm not able to reproduce this error.
